data = [
    {
        "name": "Instagram",
        "follower_count": 613,
        "description": "Streaming service",
        "country": "France",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 275,
        "description": "Fast food chain",
        "country": "Netherlands",
    },
    {
        "name": "Google",
        "follower_count": 485,
        "description": "Content creator",
        "country": "United States",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 307,
        "description": "Athlete",
        "country": "Germany",
    },
    {
        "name": "YouTube",
        "follower_count": 405,
        "description": "Fashion brand",
        "country": "Portugal",
    },
    {
        "name": "MrBeast",
        "follower_count": 435,
        "description": "Politician",
        "country": "Mexico",
    },
    {
        "name": "Tesla",
        "follower_count": 301,
        "description": "Content creator",
        "country": "Australia",
    },
    {
        "name": "The Rock",
        "follower_count": 459,
        "description": "Fashion brand",
        "country": "France",
    },
    {
        "name": "Fortnite",
        "follower_count": 97,
        "description": "Car manufacturer",
        "country": "United States",
    },
    {
        "name": "Netflix",
        "follower_count": 454,
        "description": "Educational platform",
        "country": "China",
    },
    {
        "name": "Facebook",
        "follower_count": 516,
        "description": "Online marketplace",
        "country": "Netherlands",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 606,
        "description": "Entertainment company",
        "country": "United States",
    },
    {
        "name": "Amazon",
        "follower_count": 591,
        "description": "AI model",
        "country": "Portugal",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 315,
        "description": "Online marketplace",
        "country": "Netherlands",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 590,
        "description": "Musician",
        "country": "Italy",
    },
    {
        "name": "Elon Musk",
        "follower_count": 284,
        "description": "Online marketplace",
        "country": "Netherlands",
    },
    {
        "name": "LinkedIn",
        "follower_count": 210,
        "description": "Content creator",
        "country": "Germany",
    },
    {
        "name": "Twitter",
        "follower_count": 484,
        "description": "Video sharing platform",
        "country": "Australia",
    },
    {
        "name": "Spotify",
        "follower_count": 66,
        "description": "Social media platform",
        "country": "Germany",
    },
    {
        "name": "Apple",
        "follower_count": 541,
        "description": "Social media platform",
        "country": "Poland",
    },
    {
        "name": "NASA",
        "follower_count": 497,
        "description": "AI model",
        "country": "Canada",
    },
    {
        "name": "Bill Gates",
        "follower_count": 328,
        "description": "Online marketplace",
        "country": "Mexico",
    },
    {
        "name": "Barack Obama",
        "follower_count": 342,
        "description": "Athlete",
        "country": "Mexico",
    },
    {
        "name": "PewDiePie",
        "follower_count": 193,
        "description": "Programming language",
        "country": "Mexico",
    },
    {
        "name": "Minecraft",
        "follower_count": 525,
        "description": "Fashion brand",
        "country": "Portugal",
    },
    {
        "name": "WhatsApp",
        "follower_count": 108,
        "description": "Technology company",
        "country": "Italy",
    },
    {
        "name": "Drake",
        "follower_count": 571,
        "description": "Athlete",
        "country": "Italy",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 644,
        "description": "Singer-songwriter",
        "country": "Japan",
    },
    {
        "name": "Nike",
        "follower_count": 397,
        "description": "Footballer",
        "country": "South Korea",
    },
    {
        "name": "Red Bull",
        "follower_count": 614,
        "description": "Online marketplace",
        "country": "Spain",
    },
    {
        "name": "PlayStation",
        "follower_count": 399,
        "description": "Online marketplace",
        "country": "Portugal",
    },
    {
        "name": "Marvel Studios",
        "follower_count": 102,
        "description": "Entertainment company",
        "country": "Portugal",
    },
    {
        "name": "Zendaya",
        "follower_count": 593,
        "description": "Actor",
        "country": "China",
    },
    {
        "name": "Meta",
        "follower_count": 264,
        "description": "Social media platform",
        "country": "Mexico",
    },
    {
        "name": "Coca-Cola",
        "follower_count": 218,
        "description": "Online marketplace",
        "country": "Sweden",
    },
    {
        "name": "Nintendo",
        "follower_count": 103,
        "description": "Actor",
        "country": "United Kingdom",
    },
    {
        "name": "BBC",
        "follower_count": 506,
        "description": "Video sharing platform",
        "country": "India",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 31,
        "description": "Fast food chain",
        "country": "Poland",
    },
    {
        "name": "Rihanna",
        "follower_count": 595,
        "description": "Fast food chain",
        "country": "Australia",
    },
    {
        "name": "BMW",
        "follower_count": 341,
        "description": "Multiplayer game",
        "country": "Australia",
    },
    {
        "name": "Mercedes-Benz",
        "follower_count": 258,
        "description": "Content creator",
        "country": "Portugal",
    },
    {
        "name": "TikTok",
        "follower_count": 237,
        "description": "Entrepreneur",
        "country": "China",
    },
    {
        "name": "Oprah Winfrey",
        "follower_count": 202,
        "description": "Content creator",
        "country": "Brazil",
    },
    {
        "name": "GTA V",
        "follower_count": 527,
        "description": "YouTuber",
        "country": "Canada",
    },
    {
        "name": "Starbucks",
        "follower_count": 201,
        "description": "Car manufacturer",
        "country": "Spain",
    },
    {
        "name": "NASA",
        "follower_count": 532,
        "description": "Athlete",
        "country": "Portugal",
    },
    {
        "name": "Stephen King",
        "follower_count": 61,
        "description": "YouTuber",
        "country": "Portugal",
    },
    {
        "name": "Adobe",
        "follower_count": 430,
        "description": "Programming language",
        "country": "South Korea",
    },
    {
        "name": "HBO",
        "follower_count": 243,
        "description": "Fast food chain",
        "country": "Australia",
    },
    {
        "name": "Warner Bros",
        "follower_count": 325,
        "description": "Content creator",
        "country": "Sweden",
    },
    {
        "name": "Google Maps",
        "follower_count": 114,
        "description": "Fashion brand",
        "country": "United States",
    },
    {
        "name": "Coursera",
        "follower_count": 202,
        "description": "Online marketplace",
        "country": "Poland",
    },
    {
        "name": "Harvard",
        "follower_count": 383,
        "description": "Online marketplace",
        "country": "Netherlands",
    },
    {
        "name": "MIT",
        "follower_count": 506,
        "description": "Actor",
        "country": "South Korea",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 590,
        "description": "Fashion brand",
        "country": "Australia",
    },
    {
        "name": "Spotify",
        "follower_count": 29,
        "description": "Programming language",
        "country": "India",
    },
    {
        "name": "Snapchat",
        "follower_count": 522,
        "description": "Online marketplace",
        "country": "Mexico",
    },
    {
        "name": "Shakira",
        "follower_count": 106,
        "description": "YouTuber",
        "country": "Mexico",
    },
    {
        "name": "LeBron James",
        "follower_count": 609,
        "description": "Programming language",
        "country": "Australia",
    },
    {
        "name": "Steam",
        "follower_count": 684,
        "description": "Entrepreneur",
        "country": "Canada",
    },
    {
        "name": "Twitch",
        "follower_count": 623,
        "description": "Actor",
        "country": "China",
    },
    {
        "name": "OpenAI",
        "follower_count": 286,
        "description": "Actor",
        "country": "Australia",
    },
    {
        "name": "ChatGPT",
        "follower_count": 302,
        "description": "Video sharing platform",
        "country": "Poland",
    },
    {
        "name": "Quora",
        "follower_count": 621,
        "description": "Car manufacturer",
        "country": "Mexico",
    },
    {
        "name": "Stack Overflow",
        "follower_count": 34,
        "description": "YouTuber",
        "country": "Sweden",
    },
    {
        "name": "Python",
        "follower_count": 301,
        "description": "Politician",
        "country": "Poland",
    },
    {
        "name": "JavaScript",
        "follower_count": 669,
        "description": "Streaming service",
        "country": "Poland",
    },
    {
        "name": "Java",
        "follower_count": 504,
        "description": "Content creator",
        "country": "Netherlands",
    },
    {
        "name": "Coca-Cola",
        "follower_count": 399,
        "description": "Streaming service",
        "country": "Japan",
    },
    {
        "name": "Pepsi",
        "follower_count": 532,
        "description": "Gaming platform",
        "country": "Netherlands",
    },
    {
        "name": "Burger King",
        "follower_count": 163,
        "description": "Fashion brand",
        "country": "Canada",
    },
    {
        "name": "McDonald’s",
        "follower_count": 681,
        "description": "Footballer",
        "country": "Spain",
    },
    {
        "name": "KFC",
        "follower_count": 294,
        "description": "Athlete",
        "country": "Australia",
    },
    {
        "name": "Subway",
        "follower_count": 653,
        "description": "Gaming platform",
        "country": "Italy",
    },
    {
        "name": "Domino’s",
        "follower_count": 267,
        "description": "Fast food chain",
        "country": "India",
    },
    {
        "name": "IKEA",
        "follower_count": 680,
        "description": "Entertainment company",
        "country": "Canada",
    },
    {
        "name": "Lego",
        "follower_count": 561,
        "description": "Car manufacturer",
        "country": "Sweden",
    },
    {
        "name": "H&M",
        "follower_count": 349,
        "description": "Entrepreneur",
        "country": "Canada",
    },
    {
        "name": "Zara",
        "follower_count": 368,
        "description": "Singer-songwriter",
        "country": "Sweden",
    },
    {
        "name": "ASOS",
        "follower_count": 547,
        "description": "Entertainment company",
        "country": "Poland",
    },
    {
        "name": "Netflix",
        "follower_count": 409,
        "description": "Musician",
        "country": "Netherlands",
    },
    {
        "name": "Disney+",
        "follower_count": 225,
        "description": "Multiplayer game",
        "country": "Canada",
    },
    {
        "name": "Hulu",
        "follower_count": 68,
        "description": "Entrepreneur",
        "country": "Brazil",
    },
    {
        "name": "Prime Video",
        "follower_count": 529,
        "description": "Athlete",
        "country": "France",
    },
    {
        "name": "Tinder",
        "follower_count": 615,
        "description": "Entertainment company",
        "country": "Sweden",
    },
    {
        "name": "Bumble",
        "follower_count": 121,
        "description": "Content creator",
        "country": "Netherlands",
    },
    {
        "name": "Airbnb",
        "follower_count": 242,
        "description": "Athlete",
        "country": "South Korea",
    },
    {
        "name": "Uber",
        "follower_count": 122,
        "description": "Social media platform",
        "country": "China",
    },
    {
        "name": "Bolt",
        "follower_count": 479,
        "description": "Politician",
        "country": "Mexico",
    },
    {
        "name": "Canva",
        "follower_count": 59,
        "description": "Streaming service",
        "country": "India",
    },
    {
        "name": "Notion",
        "follower_count": 264,
        "description": "Educational platform",
        "country": "India",
    },
    {
        "name": "Figma",
        "follower_count": 118,
        "description": "Politician",
        "country": "Mexico",
    },
    {
        "name": "Adobe XD",
        "follower_count": 145,
        "description": "Programming language",
        "country": "United Kingdom",
    },
    {
        "name": "Behance",
        "follower_count": 216,
        "description": "Gaming platform",
        "country": "Poland",
    },
    {
        "name": "Deezer",
        "follower_count": 426,
        "description": "Athlete",
        "country": "India",
    },
    {
        "name": "SoundCloud",
        "follower_count": 454,
        "description": "Educational platform",
        "country": "Netherlands",
    },
    {
        "name": "Eminem",
        "follower_count": 542,
        "description": "Gaming platform",
        "country": "United Kingdom",
    },
    {
        "name": "Post Malone",
        "follower_count": 613,
        "description": "YouTuber",
        "country": "Canada",
    },
    {
        "name": "Doja Cat",
        "follower_count": 644,
        "description": "Video sharing platform",
        "country": "Poland",
    },
    {
        "name": "Travis Scott",
        "follower_count": 340,
        "description": "Programming language",
        "country": "Australia",
    },
]
